const router=require('express').Router();
const c=require('../controllers/collaborativeLearningController');
const {authMiddleware,isGestorPedagogico}=require('../middlewares/authMiddleware');
router.use(authMiddleware);
router.get('/redacao/projetos',c.projetos);
router.post('/redacao/projetos',c.salvarProjeto);
router.get('/redacao/evolucao-enem',c.evolucao);
router.get('/revisoes-pares',c.revisoesPar);
router.post('/revisoes-pares/disponibilizar',c.disponibilizarPar);
router.patch('/revisoes-pares/:id',c.responderPar);
router.post('/revisoes-pares/:id/denunciar',c.denunciar);
router.get('/gestao/alertas',isGestorPedagogico,c.alertas);
router.get('/gestao/intervencoes',isGestorPedagogico,c.intervencoes);
router.post('/gestao/intervencoes',isGestorPedagogico,c.criarIntervencao);
router.get('/gestao/grupos/sugestoes',isGestorPedagogico,c.grupos);
router.post('/gestao/grupos',isGestorPedagogico,c.criarGrupo);
router.post('/gestao/revisoes-pares',isGestorPedagogico,c.atribuirPar);
router.get('/gestao/moderacao',isGestorPedagogico,c.moderacao);
router.patch('/gestao/moderacao/:id',isGestorPedagogico,c.moderar);
module.exports=router;
