const router = require('express').Router()
const controller = require('../controllers/inteligenciaController')
const { authMiddleware } = require('../middlewares/authMiddleware')
router.use(authMiddleware)
router.get('/diagnostico', controller.diagnostico)
router.post('/diagnostico', controller.salvarDiagnostico)
router.get('/metas', controller.metas)
router.put('/metas', controller.salvarMeta)
router.get('/privacidade', controller.privacidade)
router.put('/privacidade', controller.privacidade)
router.get('/flashcards', controller.flashcards)
router.post('/flashcards', controller.criarFlashcard)
router.post('/flashcards/:idFlashcard/avaliar', controller.avaliarFlashcard)
router.get('/busca', controller.buscar)
router.get('/provas', controller.provas)
router.post('/provas', controller.criarProva)
router.get('/catalogo-provas', controller.catalogoProvas)
router.get('/simulados', controller.historicoSimulados)
router.post('/simulados', controller.gerarSimulado)
router.get('/simulados/:idSimulado', controller.obterSimulado)
router.patch('/simulados/:idSimulado', controller.salvarProgressoSimulado)
router.post('/simulados/:idSimulado/concluir', controller.concluirSimulado)
router.get('/trilhas', controller.trilhas)
module.exports = router
