import { useEffect,useState } from 'react'
import { toast } from 'react-hot-toast'
import collaborative from '../services/collaborativeService'
const etapas=[['TEMA','Tema'],['TESE','Tese'],['ARGUMENTOS','Argumentos'],['REPERTORIO','Repertório'],['INTERVENCAO','Intervenção'],['RASCUNHO','Rascunho'],['REVISAO','Revisão']]
export default function WritingWorkshop(){
 const [projeto,setProjeto]=useState({tema:'',tese:'',argumentoUm:'',argumentoDois:'',repertorio:'',intervencao:'',rascunho:'',etapa:'TEMA'}); const [evolucao,setEvolucao]=useState([]); const [aberto,setAberto]=useState(false)
 useEffect(()=>{Promise.all([collaborative.projetos(),collaborative.evolucao()]).then(([p,e])=>{if(p[0])setProjeto({...projeto,...p[0],idProjeto:p[0].id_projeto,argumentoUm:p[0].argumento_um||'',argumentoDois:p[0].argumento_dois||''});setEvolucao(e)}).catch(()=>{})},[])
 async function salvar(etapa){const salvo=await collaborative.salvarProjeto({...projeto,etapa});setProjeto({...projeto,...salvo,idProjeto:salvo.id_projeto,etapa});toast.success('Etapa da oficina salva.')}
 const ultima=evolucao.at(-1)
 return <section className="mb-6 rounded-[2rem] border border-[#7C4DFF]/20 bg-white p-5 shadow-xl dark:bg-[#1E1D3A]"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-black uppercase text-[#6D3EC5]">Oficina de redação</p><h2 className="text-xl font-black">Construa antes de escrever</h2></div><button type="button" onClick={()=>setAberto(!aberto)} className="rounded-full bg-[#6D3EC5] px-4 py-2 font-bold text-white">{aberto?'Fechar oficina':'Abrir oficina'}</button></div>{ultima&&<p className="mt-2 text-sm">Última evolução: <b>{ultima.nota}/1000</b> · {ultima.competencias.map(c=>`C${c.codigo} ${c.nota}`).join(' · ')}</p>}{aberto&&<div className="mt-4 grid gap-3"><input value={projeto.tema} onChange={e=>setProjeto({...projeto,tema:e.target.value})} placeholder="Delimite o tema" className="rounded-xl border p-3"/><textarea value={projeto.tese} onChange={e=>setProjeto({...projeto,tese:e.target.value})} placeholder="Tese: qual posição você defenderá?" className="rounded-xl border p-3"/><div className="grid gap-3 sm:grid-cols-2"><textarea value={projeto.argumentoUm} onChange={e=>setProjeto({...projeto,argumentoUm:e.target.value})} placeholder="Argumento 1" className="rounded-xl border p-3"/><textarea value={projeto.argumentoDois} onChange={e=>setProjeto({...projeto,argumentoDois:e.target.value})} placeholder="Argumento 2" className="rounded-xl border p-3"/></div><textarea value={projeto.repertorio} onChange={e=>setProjeto({...projeto,repertorio:e.target.value})} placeholder="Repertório e como ele prova seu argumento" className="rounded-xl border p-3"/><textarea value={projeto.intervencao} onChange={e=>setProjeto({...projeto,intervencao:e.target.value})} placeholder="Agente + ação + meio + finalidade" className="rounded-xl border p-3"/><textarea value={projeto.rascunho} onChange={e=>setProjeto({...projeto,rascunho:e.target.value})} placeholder="Monte o rascunho completo" className="min-h-40 rounded-xl border p-3"/><div className="flex flex-wrap gap-2">{etapas.map(([id,label])=><button type="button" key={id} onClick={()=>salvar(id)} className={`rounded-full border px-3 py-2 text-xs font-bold ${projeto.etapa===id?'bg-[#6D3EC5] text-white':''}`}>Salvar {label}</button>)}</div></div>}</section>
}
