ALTER TABLE atividades
  ADD COLUMN IF NOT EXISTS destinatarios JSON NULL AFTER questoes,
  ADD COLUMN IF NOT EXISTS atribuicao ENUM('TODOS','SELECIONADOS') NOT NULL DEFAULT 'TODOS' AFTER destinatarios;
