const model = require('../models/inteligenciaModel')
const idUsuario = (req) => req.usuario.id_usuario || req.usuario.id
const responder = (res, tarefa) => tarefa.then((dados) => res.json(dados)).catch((error) => res.status(400).json({ message: error.message || 'Não foi possível concluir a operação.' }))
exports.diagnostico = (req, res) => responder(res, model.diagnostico(idUsuario(req), String(req.query.disciplinas || '').split(',').filter(Boolean)))
exports.salvarDiagnostico = (req, res) => responder(res, model.salvarDiagnostico(idUsuario(req), req.body.respostas))
exports.metas = (req, res) => responder(res, model.metas(idUsuario(req)))
exports.salvarMeta = (req, res) => responder(res, model.salvarMeta(idUsuario(req), req.body))
exports.privacidade = (req, res) => responder(res, model.privacidade(idUsuario(req), req.method === 'PUT' ? req.body.visibilidade : null))
exports.flashcards = (req, res) => responder(res, model.listarFlashcards(idUsuario(req)))
exports.criarFlashcard = (req, res) => responder(res, model.criarFlashcard(idUsuario(req), req.body))
exports.avaliarFlashcard = (req, res) => responder(res, model.avaliarFlashcard(idUsuario(req), req.params.idFlashcard, req.body.resultado))
exports.buscar = (req, res) => responder(res, model.buscar(idUsuario(req), req.query.q))
exports.provas = (req, res) => responder(res, model.provas(idUsuario(req)))
exports.criarProva = (req, res) => responder(res, model.criarProva(idUsuario(req), req.body))
exports.trilhas = (req, res) => responder(res, model.trilhas(idUsuario(req)))
