const DB='planejai-offline-v1',VERSION=1
function currentUser(){try{const user=JSON.parse(localStorage.getItem('user')||'null');return String(user?.id_usuario||user?.id||'anonymous')}catch{return'anonymous'}}
export function scopedCacheKey(key){return`${currentUser()}:${key}`}
function open(){return new Promise((resolve,reject)=>{const req=window.indexedDB.open(DB,VERSION);req.onupgradeneeded=()=>{const db=req.result;if(!db.objectStoreNames.contains('cache'))db.createObjectStore('cache',{keyPath:'key'});if(!db.objectStoreNames.contains('queue'))db.createObjectStore('queue',{keyPath:'id',autoIncrement:true})};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
async function store(name,mode,action){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(name,mode);const result=action(tx.objectStore(name));tx.oncomplete=()=>resolve(result?.result);tx.onerror=()=>reject(tx.error)})}
export async function cachePut(key,data){return store('cache','readwrite',s=>s.put({key,data,savedAt:Date.now()}))}
export async function cacheGet(key){const db=await open();return new Promise((resolve,reject)=>{const req=db.transaction('cache').objectStore('cache').get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)})}
export async function enqueue(request){return store('queue','readwrite',s=>s.add({...request,owner:currentUser(),createdAt:Date.now(),status:'PENDING'}))}
export async function listQueue(){const db=await open();return new Promise((resolve,reject)=>{const req=db.transaction('queue').objectStore('queue').getAll();req.onsuccess=()=>resolve(req.result||[]);req.onerror=()=>reject(req.error)})}
export async function removeQueue(id){return store('queue','readwrite',s=>s.delete(id))}
export async function markConflict(item,message){return store('queue','readwrite',s=>s.put({...item,status:'CONFLICT',message}))}
export async function clearOfflineData(){const db=await open();return new Promise((resolve,reject)=>{const tx=db.transaction(['cache','queue'],'readwrite');tx.objectStore('cache').clear();tx.objectStore('queue').clear();tx.oncomplete=()=>resolve();tx.onerror=()=>reject(tx.error)})}
export async function syncQueue(){if(!window.navigator.onLine)return{synced:0,conflicts:0};const owner=currentUser();if(owner==='anonymous')return{synced:0,conflicts:0};const items=await listQueue();let synced=0,conflicts=0;for(const item of items.filter(i=>i.status==='PENDING'&&i.owner===owner)){try{const response=await fetch(`${item.baseURL}${item.url}`,{method:item.method,headers:{'Content-Type':'application/json',...(localStorage.getItem('token')?{Authorization:`Bearer ${localStorage.getItem('token')}`}:{})},body:item.data?JSON.stringify(item.data):undefined});if(response.status===409){await markConflict(item,'O servidor possui uma versão diferente. Revise antes de reenviar.');conflicts++;continue}if(response.status===401||response.status===403){await markConflict(item,'A sessão ou a permissão mudou. Entre novamente antes de revisar este envio.');conflicts++;continue}if(!response.ok)continue;await removeQueue(item.id);synced++}catch{/* permanece na fila */}}window.dispatchEvent(new window.CustomEvent('planejai:offline-sync',{detail:{synced,conflicts}}));return{synced,conflicts}}
